### ISSUE TITLE
elm-package doesn't read certificates from the 'System' keychain on OSX

### ISSUE THREAD

**Issue by jystic** [elm-lang/elm-package#100]
This is a problem with an upstream package, but I though I would add it here as well in case others had the same problem.

This is the symptom:
```
Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-lang/core 2.0.1

Do you approve of this plan? (y/n) y
Downloading elm-lang/core
failed with 'TlsException (HandshakeFailed (Error_Protocol ("certificate rejected: [SelfSigned]",True,CertificateUnknown)))' when sending request to
    <http://github.com/elm-lang/core/zipball/2.0.1/>
```

It happens because I'm going via a proxy which man-in-the-middles the connection (don't ask! haha) and so you need to have its root certificate installed in the keychain for HTTPS to work properly. Unfortunately the `x509-system` package doesn't read certificates from all the keychains yet.

Upstream ticket: https://github.com/vincenthz/hs-certificate/issues/49

**Comment by evancz** [comment]
Okay, looks like this is resolved now. Please reopen if there are still problems, and thanks for helping folks out by adding this here!
