### ISSUE TITLE
Make --yes default, add flag for being careful

### ISSUE THREAD

**Issue by jasonkuhrt** [elm-lang/elm-package#102]
I just tried `elm-package` tonight and found the CLI feedback confusing:

```
❯ elm-package install evancz/elm-html
To install evancz/elm-html I would like to add the following
dependency to elm-package.json:

    "evancz/elm-html": "3.0.0 <= v < 4.0.0"

May I add that to elm-package.json for you? (y/n)
```
- Prompting to confirm package installation is annoying. I've never seen a package manager do this.
- No line feed causes printed content to be hard to read. Distance between code and copywriting means copywriting bleeds back into CLI input and so on.
- First person language is jarring

Here is a revised version that I would have preferred:

```
❯ elm-package install evancz/elm-html

  Really install into elm-package.json? (y/n)

      "evancz/elm-html": "3.0.0 <= v < 4.0.0"
```

But I am not convinced this prompt is needed at all.

**Comment by Raynos** [comment]
Having experienced npm; I think one of its biggest faults is opting into mutating package.json with a `--save` flag.

I recommend you default into mutating the elm-package.json and add a `--no-save` flag if you want to avoid this mutation.

**Comment by jasonkuhrt** [comment]
@Raynos :+1:

**Comment by Raynos** [comment]
The only time you should prompt is on conflicts; i.e. adding A requires transitive dependency on B@X but you already have B@Y and that is not compatible.

**Comment by jasonkuhrt** [comment]
I would like to step back and hint at one reason why the current design is flawed. A tool like [Terraform](https://terraform.io/) deals with high-risk actions (CRUD actions on infrastructure) and therefore correctly prompts for confirmation about actions and also explicitly prints information about current state at key transitions (e.g. `terraform will do this`, `terraform did do this`, etc.).

Unlike terraform `elm-package` operates in a very low-risk user-space. The user's VCS (`git` etc.) protects against any serious issues. The amount of prompting that `elm-package` does should be drastically low compared to something like `terraform` but at present I would say its only marginally less.

If we want a training-wheels mode that is fine, but should be something that we can turn off. For example when `elm-platform` is installed a `~/.elmrc.yaml` file should default to include `training_wheels: true` or something.

**Comment by evancz** [comment]
How does the `--yes` flag come into this?

**Comment by jasonkuhrt** [comment]
Hey @evancz just a sketchy idea:

I could see it being reversed to `--interactive`. If each tool in the `elm-platform` has such a flag there would be consistency for the user, further aided if there was a `~/elmrc.yaml` that allowed for new defaults:

```
elm-package:
  interactive: false
elm-reactor:
  interactive: true
```

etc.

**Comment by rtfeldman** [comment]
+1 for the default being essentially what `--yes` currently does.

I think the best default here is the one that makes the UX nicest in the typical case, and only advanced users (or users of complex builds, perhaps) will want it to behave differently - and by that time, adding an `--interactive` flag should not be a significant inconvenience.

Personally I have yet to ever say "no" to any of these prompts, for what it's worth.

**Comment by eeue56** [comment]
I would like to add that most UNIX tools set a default argument through capitalizing the default choice - for example, 

```May I add that to elm-package.json for you? [Y/n]``` 

makes it so that yes is the default when no input is provided other than newline. I feel this is a pretty simple and nice addition that helps streamline the process. I've made a pull request that enables this functionality

**Comment by jasonkuhrt** [comment]
> most UNIX tools set a default argument through capitalizing the default choice

Wow now I know what the capital means, thanks : )

**Comment by evancz** [comment]
In the latest version, adding packages does not cause any prompts. But changing or removing existing dependencies *does* ask for permission. That seems like a reasonable compromise to me.
