### ISSUE TITLE
No error on invalid source-directories in elm-package.json

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-package#103]
If I specify an invalid path in source-directories, for example a directory that doesn't exist, neither `elm-package` nor `elm-make` complains about this. Given my general experience of "Elm tells me when something isn't sanely configured," this seemed unintentional.

**Comment by mgold** [comment]
A more concrete example: if I set ask for version 2.2.0 of core (which does not currently exist), then I am told `Packages configured successfully!` when `elm-stuff/packages/` is empty (having deleted `elm-stuff` prior to running `elm package install`).

**Comment by mgold** [comment]
Might be related to #86.

**Comment by evancz** [comment]
In the 0.19 version I added code to detect if your `source-directories` are missing. The error is like this:

```
Error: The "source-directories" in your elm.json lists the following directory:

    "../this/that"

I cannot find that directory though! Is it missing? Is there a typo?
```
