### ISSUE TITLE
Design public API for writing native code

### ISSUE THREAD

**Issue by thSoft** [elm-lang/elm-package#105]
With the introduction of Tasks, it is possible to create a publicly available route for writing native code that has effects.

There seem to be three major category of interop:

  * Graphics bindings (elm-html, elm-webgl, elements, collage, etc.) that tend to do a decent amount of crazy stuff in JS.
  * Ports where you can talk to whatever crazy stuff is out there as long as a client-server relationship is possible.
  * Wrapping up an effectful JS API with tasks, where the mapping to Elm may be relatively simple.

This would address the last case, possibly the first one as well.

Let's use this issue to gather examples of existing packages and desired packages that would fit into these cases. This will help us design for the kinds of things people actually need to do.

**Comment by evancz** [comment]
This has not been effective in tracking progress on this so far. I will be focusing on this a lot after 0.16 and I'd rather not track it here.

**Comment by thSoft** [comment]
Is this tracked anywhere now?

**Comment by thSoft** [comment]
Thanks for the pointer, I like the overall direction of providing a set of Web API "primitives" and writing only Elm code on top of them. (Sorry for seeming impatient, I was just asking for information because I hadn’t seen this write-up.)
