### ISSUE TITLE
incorrect git tag is not flagged as an error

### ISSUE THREAD

**Issue by avh4** [elm-lang/elm-package#106]
I forked a package that was previously published under a different github account with three published version (1.0.0, 1.1.0, 2.0.0).  My fork had git tags for those versions, even though I had never published under my github account.  When I published the first time, I was prompted to change the version number back to 1.0.0, which I did.  Then the package was published, even though the 1.0.0 tag in my repo did not correspond to what was being published.  I would expect an error in this case prompting me to correct that tag on my repository before publishing succeeds.

**Comment by mgold** [comment]
Is this the same as #110?

**Comment by avh4** [comment]
@mgold I think it's related, if not the same.  In #110, I'm not sure how you're expecting it to know which tag to use.  I believe the current behavior is that `elm-package` will read the version from `elm-package.json`, and then verify that a tag of that name exists.  I believe it ought to also verify that your currently checked-out branch matches what the tag points to.

**Comment by mgold** [comment]
> I believe the current behavior is that `elm-package` will read the version from `elm-package.json`, and then verify that a tag of that name exists.
I've managed to release versions where the release number is right, but `elm-package.json` is wrong; this is #110. I would therefore assume that it's looking at the current branch but I'm not sure. A few other problems: it won't verify that the files it needs are checked in to git (#114), and I've also seen something weird where the tag is generates isn't on master.

I think we can all agree that it should enforce consistency across the board, and it's just a matter of testing to smooth out the rough edges.

**Comment by evancz** [comment]
This will be checked by 0.19. It looks at the tag on github and makes sure it matches the commit and code you are looking at locally.
