### ISSUE TITLE
Developer dependencies

### ISSUE THREAD

**Issue by jagregory** [elm-lang/elm-package#108]
I have dependencies like elm-test which people consuming my package have no need for, but are required if you want to contribute to the package or run examples locally. Is there a way to specify dependencies of a package which are only used at development time?

For example Node has [devDependencies](https://docs.npmjs.com/files/package.json#devdependencies), which are only installed if you clone the project and run `npm install` but not if you install the package as a dependency.

**Comment by chendrix** [comment]
:+1: I think this is necessary if we're going to have better support for package testing.

**Comment by hughfdjackson** [comment]
+1 from me - this would be very useful! 

I've just cloned Signal-Extras to see if adding a function would work well, and had to re-install Elm-Test, without adding it to the elm-package.json - it's a bit of an unintuitive contribution flow.

**Comment by evancz** [comment]
There is no easy way to do this right now. As support for `elm-test` comes into the Elm Platform a feature like this is planned.

**Comment by evancz** [comment]
Will be part of a more coherent plan like https://github.com/elm-lang/elm-make/issues/59
