### ISSUE TITLE
No error on elm-package.json version != tag

### ISSUE THREAD

**Issue by mgold** [elm-lang/elm-package#110]
It seems that publishing does not verify the version field of elm-package.json matches the release number of the tag. As of this writing, I have [a library](http://package.elm-lang.org/packages/mgold/elm-nonempty-list/1.2.0) at 1.2.0 that seems to be working fine, except that the [version field](https://github.com/mgold/elm-nonempty-list/blob/master/elm-package.json#L2) is wrong.

**Comment by jvoigtlaender** [comment]
Apparently this problem is fixed? [This exchange](https://github.com/eeue56/elm-flat-matrix/pull/2#issuecomment-178558696) suggests so.

**Comment by mgold** [comment]
Perhaps, someone should try it and see.

**Comment by jvoigtlaender** [comment]
Doesn't my link above indicate that somebody as tried and seen?

Unless you mean that somebody should try the exact conditions that failed for you. That is, somebody should try it with your package. In which case that somebody would have to be you.

**Comment by evancz** [comment]
I believe this is fixed with my 0.19 binaries. If we can observe it again, we should open a new issue.
