### ISSUE TITLE
No message when API has not changed

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-package#111]
If I run this, it would be great to see explicit acknowledgement that there were no API changes:

``` bash
$ elm package diff TheSeamau5/elm-shrink 2.2.0 2.2.1

Comparing TheSeamau5/elm-shrink 2.2.0 to 2.2.1...
This is a PATCH change.
```

Something like adding this at the bottom:

``` bash
There are no API changes between these versions.
```

**Comment by evancz** [comment]
Should be resolved in 0.19. I am seeing the following:

```
$ elm diff TheSeamau5/elm-shrink 2.2.0 2.2.1
No API changes detected, so this is a PATCH change.
```

With some pretty colors I cannot show in this format though :)
