### ISSUE TITLE
elm-package publish allows revision where an exposed module is missing

### ISSUE THREAD

**Issue by Apanatshka** [elm-lang/elm-package#114]
I managed to publish [signal-extra 5.2.0](http://package.elm-lang.org/packages/Apanatshka/elm-signal-extra/5.2.0/) with the new [Signal.Fun](http://package.elm-lang.org/packages/Apanatshka/elm-signal-extra/5.2.0/Signal-Fun) module, but under that tag the [Fun.elm file isn't present](https://github.com/Apanatshka/elm-signal-extra/tree/5.2.0/src/Signal). I guess I forgot to put that file in the commit. 
This situation sounds like something elm-package should check and disallow, right?

**Comment by evancz** [comment]
Closing in favor of the other one. Thanks for the report!
