### ISSUE TITLE
elm-package publish allows elm-package.json version that doesn't match the tag

### ISSUE THREAD

**Issue by Apanatshka** [elm-lang/elm-package#117]
I just noticed that I published [signal-extra version 5.3.0 with version 5.2.1 in the elm-package.json](https://github.com/Apanatshka/elm-signal-extra/blob/5.3.0/elm-package.json#L2). Simply by forgetting to commit and push the version bump. No warnings or errors were given by elm-package. 

Basically I merged a PR on github. Pulled the changes. Did `elm package bump`, now my new version is in elm-package.json but not committed and pushed yet. That part I forgot, I simply tagged the merge commit with 5.3.0, pushed the tag and did `elm package publish`. 
**Expected behaviour**: error on the version number in elm-package.json, which doesn't match the version of the git tag. 
**Actual behaviour**: no complaints, it was just published. I imagine people that try to use 5.3.0 will get weird issues because the downloaded code says it's version 5.2.1. (I just published 5.4.0 so it probably won't bother anyone anymore)

**Comment by evancz** [comment]
Couldn't you move the tag to the right place? But yeah, there should be checks for this, thanks for the report. Is there an issue open describing the same thing? I don't recall.

**Comment by Apanatshka** [comment]
I didn't find out until I'd already merged another PR. I don't want to go into rewriting history and moving tags to fix a version that isn't the latest anymore. 
Yes, I see now that [this a duplicate](https://github.com/elm-lang/elm-package/issues/110), sorry!

**Comment by evancz** [comment]
No problem, thanks for the report!
