### ISSUE TITLE
How does elm-version work?

### ISSUE THREAD

**Issue by Raynos** [elm-lang/elm-package#12]
The NPM and node community used to have a field called

```json
{ 
  "engines": { "node": "0.6.x" }
}
```

A lot of modules on npm said they only worked on 0.6 but also worked on 0.8 and 0.10. However npm used to not allow you to install modules whose engines field did not match your current node version.

This caused great friction, since module authors didn't maintain their modules actively enough and people using odd versions of node (0.7, 0.9, the beta versions) couldn't install them either.

The engines field in npm now warns if you install a module that doesnt match your node version. npm does have an `engineStrict` flag that allows module authors to enforce the node version match strictly

Reference: 

 - https://github.com/isaacs/npm/issues/3662#issuecomment-21142618
 - https://github.com/isaacs/npm/blob/c5dc74ff7be3c648dba7f875bb4558493493885f/doc/files/package.json.md#engines
 - https://github.com/isaacs/npm/blob/324d912e7d6084e2ccbfcccec5abd53a889402e6/lib/npm.js#L63

**Comment by evancz** [comment]
This is how things work. If you are using Elm 0.15.1 and a package lists its `elm-version` bound such that this is not included, that package cannot be installed.
