### ISSUE TITLE
elm package install overwrites nonstandard JSON keys

### ISSUE THREAD

**Issue by dnalot** [elm-lang/elm-package#120]
The Sublime plugin stores build info under a `sublime-build` key in `elm-package.json`. That key disappears after `elm package install` updates `dependencies`. CC @deadfoxygrandpa

**Comment by kdz** [comment]
I just got bitten by this for the third time this week. I did an `elm package install`, agreed to the changes, and lost my Sublime settings. Here were elm's proposed changes, and the resulting loss of data in `elm-package.json`.

![image](https://cloud.githubusercontent.com/assets/4351330/10567165/af3a2db6-75c1-11e5-9d49-3da9a8a7f944.png)

![image](https://cloud.githubusercontent.com/assets/4351330/10567171/ba5f7426-75c1-11e5-9260-29445201668f.png)

**Comment by evancz** [comment]
I think https://github.com/elm-lang/elm-make/issues/59 is going to add the particular things you need. I'm not sold on just allowing arbitrary keys in there at this point though. Thanks for the report, let's revisit the idea of keeping random keys is needed a second time.

**Comment by dnalot** [comment]
I suspect the new schema will still obviate plugins' desire to know which page to preview within the editor. Because Elm isn't strongly rooted within the Node ecosystem we couldn't assume `package.json`. We discussed editor specific alternatives like `*.sublime-project` but they're not commonly used either. I'm passing the torch so n.b. for the next maintainer.
