### ISSUE TITLE
elm-package can't find git

### ISSUE THREAD

**Issue by EdAyers** [elm-lang/elm-package#125]
Hi, I'm on windows 10 and I have git installed but if I try and run elm-package.exe I get the following error:

```
The REPL relies on git to download libraries and manage versions.
    It appears that you do not have git installed though!
    Get it from <http://git-scm.com/downloads> to continue.
```
What environment variable is elm-package using to find git? The git executable is in `C:\Program Files (x86)\Git\bin` and I have the `PATH` and the `GIT` environment variables including that folder.

**Comment by evancz** [comment]
elm-package should just be trying to run "git" in the current context. So you can call the `git` command in the same directory that you call `elm-package`?

**Comment by EdAyers** [comment]
I can call the git command in the same directory.

**Comment by evancz** [comment]
I'm not sure what the issue is then. I wonder if there is something specific to Windows 10? Or since the tool is written in Haskell, perhaps the support for calling commands on Windows 10 is not in some library there yet? I don't really have any special insight here unfortunately.

**Comment by MajorWalrus** [comment]
Having the same issue. I tried running elm command as an admin, but that didn't help.

**Comment by MajorWalrus** [comment]
I found a work-around that works for me. Add this value to your Path variable: `C:\Program Files\Git\bin\`.

That once done close and reopen any cmd prompts you have open. Then test the new value in Path by just running `git` at a new cmd prompt. If you see the git instructions you should be all set.

At that point just run elm package command again.

**Comment by evancz** [comment]
Latest version of `elm-package` does not require `git` anymore.

**Comment by kostadinnm** [comment]
Hello, Evan. I really appreciate your work.

Here is what I get when I run `elm-package --version`:
![2016-06-16 12_47_41-greenshot](https://cloud.githubusercontent.com/assets/18436405/16112693/2e5511f2-33c1-11e6-9ced-b76b4e5ca301.png)
As you can see, I am using the latest version(by the time you've written the comment) - 0.17. That one came with the windows installer. Shall I try building 0.17.1 from source?!

With regards,
Kostadin

**Comment by evancz** [comment]
By latest I meant 0.17.1. Don't bother building from source. It's hard and error prone. It'll be out pretty soon.
