### ISSUE TITLE
Infer intial repository from .git/config

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-package#131]
Currently when an `elm-package.json` file is created from scratch, it has a default `repository` field of `https://github.com/USER/PROJECT.git` in all cases.

This field could be helpfully inferred if you are initializing a package in a directory that is already configured with a Git remote. If there is a `.git/config` file relative to where `elm-package.json` will be created, that `config` file may include one or more `[remote]` sections like so:

```
[remote "origin"]
        url = git@github.com:rtfeldman/elm-validate.git
        fetch = +refs/heads/*:refs/remotes/origin/*
```

`elm-package.json` could be initialized to the `url` of the first such `[remote]` encountered in `config`, falling back on the current behavior.

**Comment by evancz** [comment]
Cool idea! I wonder if we can get the global "user name" if one is set as well. I think git has something like this.

**Comment by Apanatshka** [comment]
You could also make the `init` process more interactive, like a:

```
Inferring git repo url as:

    https://github.com/rtfeldman/elm-validate.git

Is that right? [Y/n]
> n
Oh ok, please type the correct URL then:
> 
```

with a `-y` command to make it non-interactive. 

I prefer that over a process that tells me the files it creates contains dummy values I need to fill in.

**Comment by evancz** [comment]
Okay, linked to this from an issue tracking this sort of thing. Thanks!
