### ISSUE TITLE
Empty exposed-modules can sneak onto server

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-package#133]
1. I tried publishing 1.0.0 of `elm-validate` and got an error message saying there were no exposed modules (I'd forgotten to list one).
2. I fixed that in `elm-package.json` and force-pushed the `1.0.0` tag.
3. I ran `elm package publish` again and it succeeded, publishing `1.0.0`.
4. When I then installed `1.0.0` of the package in another project and attempted to use it, its modules were not exposed after all.
5. In `elm-stuff/packages/rtfeldman/elm-validate` it had the original `elm-package.json` with no exposed modules.

Bumping the version number to 1.0.1 and publishing again fixed it.

**Comment by evancz** [comment]
I think there's an issue open about this. That we should grab the tag, not the local stuff. Can you check and close this / add this to that issue?

**Comment by rtfeldman** [comment]
Yep! Closing as duplicate of https://github.com/elm-lang/elm-package/issues/106
