### ISSUE TITLE
elm package bump exits prematurely

### ISSUE THREAD

**Issue by jessitron** [elm-lang/elm-package#137]
It asks me a question and then exits! It does not wait for my response!

    elm-http jessitron$ elm package bump
    Error: failure when running: elm-make --docs=elm-stuff/documentation.json
    elm-make: <stdin>: hGetLine: end of file
    Some new packages are needed. Here is the upgrade plan.
      Install:
        elm-lang/core 2.1.0
    Do you approve of this plan? (y/n)
    elm-http jessitron$

This is with 0.15.1 of elm-package

**Comment by jessitron** [comment]
If I run `elm-make --docs=elm-stuff/documentation.json` separately, it requests permission to upgrade and then works.

**Comment by evancz** [comment]
Can you say more about what is going on here? I have no idea how to reproduce this or what the particular context is. `elm-package bump` has never done this for me, so I need more info to figure out what is going on in your case.

What OS? What is the project like? Is it possible to get a single file that can reproduce this? Does it need a variety of factors? What are those factors exactly?

**Comment by jessitron** [comment]
Ah! reproduced it.
I was doing this in a fresh checkout of elm-http (not intelligently), and if I have never run elm-make in that project, then "elm package bump" fails in this way.
To make it happen again I had to `rm -rf elm-stuff`

**Comment by jvoigtlaender** [comment]
PR #140 may fix this.

**Comment by evancz** [comment]
Should be fixed by #137, thanks for the report!
