### ISSUE TITLE
publish: uncommitted changes lead to inaccurate tagging

### ISSUE THREAD

**Issue by jessitron** [elm-lang/elm-package#138]
When I publish a package, elm-package insists that I create a tag. That's good, but if I have uncommitted changes, then the tag gets created in the wrong place. as far as I could tell, my local files are the ones that are published, even when the tag is pointing to something different.

Maybe refuse to publish if there are uncommitted changes?
or publish from the tag instead of local?

**Comment by Apanatshka** [comment]
Though not as well-written as this, #114 is basically about the same issue.

**Comment by evancz** [comment]
In 0.19, the publish process checks that there are no uncommitted changes and that you are looking at the same code that is tagged on github.
