### ISSUE TITLE
strange FailedConnectionException

### ISSUE THREAD

**Issue by flip111** [elm-lang/elm-package#141]
Just to try i added `"circuithub/elm-list-extra": "3.7.0 <= v <= 3.7.0"` between line 13 and 14 in this file https://github.com/evancz/elm-architecture-tutorial/blob/master/examples/1/elm-package.json then run `elm-package install` and i get

```
» elm-package install
Some new packages are needed. Here is the upgrade plan.

  Install:
    circuithub/elm-list-extra 3.7.0

Do you approve of this plan? (y/n) y
Downloading circuithub/elm-list-extra

Error: failed with 'FailedConnectionException "codeload.github.com" 443' when sending request to
    <http://github.com/circuithub/elm-list-extra/zipball/3.7.0/>
```

It's strange because the zipball link works in my browser

**Comment by jvoigtlaender** [comment]
Same issue as https://github.com/elm-lang/elm-package/issues/115?

**Comment by flip111** [comment]
i don't think so because i'm not using vagrant or docker

**Comment by jvoigtlaender** [comment]
Well, look again. In particular in the mailing list thread linked there. People didn't have this *just* with vagrant or docker. For example, one person had it when having another Elm tool open concurrently in a separate terminal.

**Comment by flip111** [comment]
ah yes i had the elm-repl running in another terminal, this workaround helped. thx
