### ISSUE TITLE
The "repository" field restrictions

### ISSUE THREAD

**Issue by nikita-volkov** [elm-lang/elm-package#144]
While running `elm-package install` on a project, which had the "repository" field set to something other than GitHub, I got the following error:

    the 'repository' field must point to a GitHub project for now, something
    like <https://github.com/USER/PROJECT.git> where USER is your GitHub name
    and PROJECT is the repo you want to upload.

The command would neither run successfully if I removed the field altogether.

Those seem like very unpractical restrictions. Now instead of specifying the real repository of the project I have to work around the issue by pointing to some GitHub repo, which does not exist.

**Comment by evancz** [comment]
This should be addressed by https://github.com/elm-lang/elm-make/issues/59. We don't support not-github for now, but putting in a dummy repo is the stopgap measure to go with for now.
