### ISSUE TITLE
elm-package install command fails without error

### ISSUE THREAD

**Issue by gwely** [elm-lang/elm-package#149]
I am following Richard Feldman's tuturial [here](noredinktech.tumblr.com/post/126978281075/walkthrough-introducing-elm-to-a-js-web-app) and have run into an issue. I've installed elm via `npm install -g elm`. 

When I run `elm-package install elm-lang/core` this is the output:

```
λ elm-package install elm-lang/core
Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-lang/core 2.1.0

Do you approve of this plan? (y/n) y
Downloading elm-lang/core

λ
```

The command created the `elm-package.json` file and the `elm-stuff` directory with `packages/elm-lang/core`, but `/core` is empty.

I am on Windows Server 2008 R2. My elm version info:

```
elm-make 0.2 (Elm Platform 0.15.1)
Elm Package Manager 0.5.1 (Elm Platform 0.15.1)
```

**Comment by gwely** [comment]
I went back and uninstalled elm from npm via `npm uninstall -g elm` then used the Windows installer found [here](http://elm-lang.org/install).

The `elm-package install` command was still not working. It would result in a generic Windows error. When I chose to debug, it output the following error:

```
Error: failed with 'FailedConnectionException "github.com" 443' when sending request to
    <http://github.com/elm-lang/core/zipball/2.1.0/>
```

Using @agrafix's [python script](https://gist.githubusercontent.com/agrafix/11d33acb137646b317d1/raw/b69134d400d59823c5d2cc9a196f09f3c1c1bd55/elm-install.py) found in [this issue](https://github.com/elm-lang/elm-package/issues/115) the install worked.

```
.\elm-install.py elm-lang/core 2.1.0
```

**Comment by ikkeps** [comment]
I have the same problem:

```
Some new packages are needed. Here is the upgrade plan.

  Install:
    Fresheyeball/elm-return 4.0.0
  Remove:
    debois/elm-dom
    debois/elm-mdl
    debois/elm-parts
    elm-lang/dom
    elm-lang/window

Do you approve of this plan? [Y/n] y
Starting downloads...

  ✗ Fresheyeball/elm-return 4.0.0
[91mError: The following HTTP request failed.
<https://github.com/Fresheyeball/elm-return/zipball/4.0.0/>

FailedConnectionException "codeload.github.com" 443
```

Just installed fresh elm by
```
 sudo npm install -g elm
```
And problem persists. 
OS: Ubuntu 14.04 (yes, this is kinda old)

curl also does not work 

```
 curl -L -v https://github.com/Fresheyeball/elm-return/zipball/4.0.0/
...
* Issue another request to this URL: 'https://codeload.github.com/Fresheyeball/elm-return/legacy.zip/4.0.0'
* Hostname was NOT found in DNS cache
*   Trying 192.30.252.147...
```
and hangs. I am from Russia, currently no github servers is blocked from here.
Proxy usage fixes the problem, but only if I use python script mentioned above. elm-package seems to be ignore https_proxy env variable.
