### ISSUE TITLE
automate process of tagging a version in git

### ISSUE THREAD

**Issue by Raynos** [elm-lang/elm-package#15]
Your documentation says you should use git to tag your versions for installs and publishes to work.

Having an `elm-get version` command will make manually keeping your git tags in sync with the information in the dependencies.json a lot easier.

Basically the command should create a commit with the version name and a tag for you.

You can also implement `elm-get version patch/minor/major` to update the dependencies.json with a new version, create a commit & a tag.

See [npm version](https://github.com/isaacs/npm/blob/master/doc/cli/npm-version.md)

**Comment by evancz** [comment]
I see how that'd be more convenient, but I do not want to mess with anyones version control. I'm sure people feel all different ways, and I'd rather folks know exactly what's happening to them.
