### ISSUE TITLE
Install multiple packages from the CLI

### ISSUE THREAD

**Issue by chrisbuttery** [elm-lang/elm-package#150]
Like npm, it would be nice to be able to install multiple packages from the CLI.

```
% elm package install evancz/elm-html evancz/start-app
```

Obviously this screws up the existing pattern, as we'd have to rethink specifying versions.

```
% elm package install evancz/elm-html@4.0.2 evancz/start-app@2.0.2
```

Perhaps then the command should read ...

```
% elm install ...
```

Obviously you can define all packages in your `elm-package.json` and just run `elm package install` to install them... which is great.

Anyhoo... just a thought :)

**Comment by chrisbuttery** [comment]
Reopening this again after discussing the possibility of installing multiple packages via CLI at the Elm Hackathon SF.

**Comment by mgold** [comment]
+1

It's not that hard to tell the difference between a package and a version, so having them interspersed (with no two versions adjacent) would be fine. That is, I think the `@` is overkill.

**Comment by evancz** [comment]
I don't think I am going to add this anytime soon, particularly because of the need for more complex parsing of args (either being clever or changing something that's not broken)

I don't see the huge problem with (1) adding them to you elm-package.json directly or (2) doing it on separate lines.
