### ISSUE TITLE
GitHub outage produced unfriendly Haskell error

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-package#151]
This error seems most likely to have happened because of a GitHub outage, but if so, it would be good if it could give a more descriptive error like "Error downloading package data from [url]"

```
16:19:50  Errno::EIO: Input/output error @ io_fillbuf - fd:25 /dev/pts/11
```

**Comment by evancz** [comment]
Yeah, it looked like all of github was down for a few minutes there. I think this error is actually from deeper in the HTTP library that we depend on, I certainly had no hand in that.

I *guess* a resource disappeared mid-request in an unexpected way. I am not sure how possible it is to fix this, and I am pretty certain I do not own the code that triggered this. Maybe we can catch this anyway. I am not sure.

**Comment by evancz** [comment]
We already have code that will catch any Haskell `IO` errors during the HTTP request. They say something like this:

```
The following HTTP request failed:

    <https://github.com/elm-lang/core/zipball/5.1.1>

Here is the error message I was able to extract:

    whatever the IO error was
```

That suggests that the request completed successfully, returning a bunch of buffers that we read from lazily. The failure must have manifested when those buffers did not contain the data they promised?

Without more info, I don't think I can pursue this further.

Separately, issue #276 is pushing towards a retry mechanism, and with per-user caching, there should just be many fewer downloads overall. So I think it makes sense to close and open a new one if we can observe this again with 0.19
