### ISSUE TITLE
() (unit type) gets exported to HTML documentation as )

### ISSUE THREAD

**Issue by thSoft** [elm-lang/elm-package#153]
See e.g. http://package.elm-lang.org/packages/evancz/elm-effects/2.0.0/Effects#toTask

**Comment by jvoigtlaender** [comment]
Known: https://github.com/elm-lang/package.elm-lang.org/issues/66, and fixed: https://github.com/elm-lang/elm-compiler/pull/1075.

**Comment by thSoft** [comment]
Sorry, I did not know it stems from the compiler.

**Comment by evancz** [comment]
No worries :) And let me know specific pages where you stuff is messed up. I can try to fix it by hand for now.

**Comment by jvoigtlaender** [comment]
@evancz, is it really worth fixing this by hand on individual pages? I'll make a proposal over at https://github.com/elm-lang/package.elm-lang.org that should fix this issue for all existing pages as a side effect.
