### ISSUE TITLE
Add OpenSearch support

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-package#154]
This makes it so when users type in package.elm-lang.org in Chrome and hit Tab, it will automatically be searching package.elm-lang.org.

It turns out this is pretty simple:

http://stackoverflow.com/questions/7630144/how-to-add-google-chrome-omnibox-search-support-for-your-site

**Comment by evancz** [comment]
Better to track somewhere else.

**Comment by rtfeldman** [comment]
👍 Moved to https://github.com/elm-lang/package.elm-lang.org/issues/243
