### ISSUE TITLE
If there are several matching patch versions available, not only the latest patch should be tried

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-package#157]
This surfaced [here](https://groups.google.com/d/msg/elm-discuss/MrmcITtA94I/Kq_rSX81DgAJ) a while ago, but I think it was not brought up as an issue in the repo, nor was it fixed meanwhile?

It has caused problems for some people since then (I remember answering questions related to this several times), the latest incidence is [this](https://groups.google.com/d/msg/elm-discuss/u8c_wFjtGYw/20L4nN8KAwAJ).

**Comment by evancz** [comment]
Thanks for filing this here, I forgot to fix this!
