### ISSUE TITLE
Field change: exposed-modules to exported-modules

### ISSUE THREAD

**Issue by mgold** [elm-lang/elm-package#158]
Related to elm-lang/elm-compiler#1124, we should be more precise about the definition of _exposed_ vs. _exported_. The `exposed-modules` field of `elm-package.json` should be renamed `exported-modules` (in a backwards compatible way). This will clarify the distinction between exporting a module for others and importing it with values exposed for your own use.

**Comment by evancz** [comment]
I kind of think this distinction is weird. It does not feel like it has a clear uniform meaning across all the things you are interested in. Overall, I'm not sure if making a subtle weird distinction is worth the confusion it'll cost in having to tell everyone the subtle weird distinction so they can remember which is which.

Anyway, point is https://github.com/elm-lang/elm-make/issues/59 has discussion of this, so now there's a link and it'll be in the feed when I go to work on that stuff. I don't want to cause a side-discussion, so please do not add additional comments there. The backlink will work!
