### ISSUE TITLE
Retrying when connection to GitHub fails

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-package#163]
Occasionally a connection to GitHub will fail when attempting to download packages:

```
elm package install
Some new packages are needed. Here is the upgrade plan.

  Install:
    NoRedInk/elm-lazy-list 1.0.0
    NoRedInk/elm-random-extra 1.0.0
    NoRedInk/elm-shrink 1.0.1
    NoRedInk/elm-task-extra 1.0.0
    deadfoxygrandpa/Elm-Test 1.0.4
    elm-lang/core 2.1.0
    maxsnew/IO 1.0.1
    maxsnew/lazy 1.0.1

Do you approve of this plan? (y/n) y
Downloading NoRedInk/elm-lazy-list
Downloading NoRedInk/elm-random-extra
Downloading NoRedInk/elm-shrink
Downloading NoRedInk/elm-task-extra
Downloading deadfoxygrandpa/Elm-Test

Error: failed with 'TlsExceptionHostPort (HandshakeFailed (Error_Packet_unexpected "Alert [(AlertLevel_Fatal,BadRecordMac)]" " expected: change cipher")) "github.com" 80' when sending request to
    <http://github.com/deadfoxygrandpa/Elm-Test/zipball/1.0.4/>
```

Because this is just a network fault, generally speaking all you have to do to fix this is to re-run `elm package install`, and the second time around it succeeds.

However, this is problematic on CI servers because they run `elm package install` so often. Add up enough dependencies and enough builds, and you start getting a lot of failed builds because of these random network issues.

We solved this by manually wrapping all our `elm package install` commands in a retry script that attempts it up to 5 times before giving up, but it would be much preferred if `elm-package` implemented retrying itself around individual downloads instead of the command as a whole.

**Comment by joeandaverde** [comment]
I'm having this issue regularly on CircleCI. Would you mind sharing your script?

**Comment by rtfeldman** [comment]
@joeandaverde sure! https://gist.github.com/rtfeldman/eddddb013edc02fa14a3

**Comment by sporto** [comment]
I am having luck dealing with this issue with a bash script like this:

```sh
#!/bin/bash

n=0
until [ $n -ge 5 ]
do
  elm package install -y && break
  n=$[$n+1]
  sleep 15
done
```

**Comment by evancz** [comment]
My understanding is:

  - There has been a fix in the underlying Haskell library that made this particularly flaky.
  - We started using the `https` version of github URLs which avoid a redirect in the first place, also making things less flaky.

I think it makes sense to reopen this if we see the issues persist in 0.17. Or reopen if folks can find precedent for doing this in projects like `npm` or `brew` or whatever else. My gut says that is not what they do, but I do not know.

**Comment by garbas** [comment]
I'd like to cast my vote on having a retry policy in elm-package when downloading.

The following language specific package managers I checked have retry logic *builtin*:
 - [pip](https://github.com/pypa/pip/blob/master/pip/download.py#L341)
 - [stack](https://github.com/commercialhaskell/stack/blob/master/src/Stack/Fetch.hs#L530)
 - [yarn](https://github.com/yarnpkg/yarn/blob/master/src/util/request-manager.js#L55)
 - [bundle](http://bundler.io/v1.5/bundle_install.html) - has a ``--retry`` option
 - apt-get does not have to any retry logic, but aptitude has it.
 - rpm does not have retry logic but yum have it.

It looks quite common to retry when a connection error happens. And there might be many reasons why connection can fail, which has nothing to do with code and I see no better way but to retry.

/cc @evancz
