### ISSUE TITLE
Unparseable elm-package.json files are preserved in ~/.elm/package/...

### ISSUE THREAD

**Issue by ormsbee** [elm-lang/elm-package#164]
In https://github.com/evancz/start-app/issues/36, I tried to install `evancz/start-app`. I was connected to a hotel wifi at the time, and the proxy redirected elm-package's request for start-app's `elm-package.json` to a login page. This caused this [error](https://github.com/elm-lang/elm-package/issues/142):

```
Error: Unable to get elm-package.json for evancz/start-app 2.0.1
Failed reading: satisfy
```

However, the HTML for the login page was still saved to `~/.elm/package/evancz/start-app/2.0.1/elm-package.json` and every subsequent attempt to install start-app 2.0.1 would die while trying to parse this as JSON.

Deleting the file clears up everything. It seems like the right thing to do would be to delete (or move) the locally cached elm-package.json file if it's malformed? My apologies that this doesn't come with a corresponding PR -- I'm afraid I don't know Haskell.

**Comment by evancz** [comment]
Thanks for reporting this! With the recent changes, you should see a message like this:

```
I just fetched elm-package.json for evancz/start-app 2.0.1, but I cannot read
the contents.

Maybe it is a very old file, and the file format changed since then? Or maybe
you are at a hotels or airports where they hijack your HTTP requests and
redirect you to some log in page?
```

And it will remove the bad file. So when you try later, you actually will try again.

**Comment by rofrol** [comment]
On Windows delete `%USERPROFILE%\AppData\Roaming\elm\package\<author>\<package>` or wait for elm-0.17.1
