### ISSUE TITLE
Error: Unable to find a set of packages that will work with your constraints.

### ISSUE THREAD

**Issue by gyzerok** [elm-lang/elm-package#167]
Subj

**Comment by jvoigtlaender** [comment]
More information about what you were trying to do will be needed to do anything here. For example, how does your `elm-package.json` file look? What command(s) did you issue? Starting in an empty directory?

**Comment by gyzerok** [comment]
@jvoigtlaender Sorry for the lack of info.

```json
{
    "version": "1.0.0",
    "summary": "helpful summary of your project, less than 80 characters",
    "repository": "https://github.com/USER/PROJECT.git",
    "license": "BSD3",
    "source-directories": [
        "./src"
    ],
    "exposed-modules": [],
    "dependencies": {
        "elm-lang/core": "3.0.0 <= v < 4.0.0",
        "evancz/elm-html": "4.0.2 <= v < 5.0.0"
    },
    "elm-version": "0.15.1 <= v < 0.16.0"
}
```

I'm running in this issue while executing `elm-package install evancz/elm-http`

**Comment by jvoigtlaender** [comment]
Okay. As seen [here](https://github.com/elm-lang/core/blob/3.0.0/elm-package.json), version `3.0.0` of `core` depends on at least version `0.16.0` of Elm. So `elm-lang/core": "3.0.0 <= v < 4.0.0"` is incompatible with `"elm-version": "0.15.1 <= v < 0.16.0"`. You have to change one of these constraints.

Of course, it would be nice if the error message had told you so. There is some issue already open either here or in the `elm-make` repo which is tracking this. So at some point there will hopefully be a more informative error in such cases.

Does this resolve the present issue?

**Comment by gyzerok** [comment]
@jvoigtlaender Yes, big thanks!

**Comment by vherasme** [comment]
Hi. could you please tell me how to solve this problem? I am starting to learn elm and I cannot install the html package on windows
