### ISSUE TITLE
New "Unable to find a set of packages that will work with your constraints" errors

### ISSUE THREAD

**Issue by amitaibu** [elm-lang/elm-package#170]
I wasn't able to reproduce this error locally (I'm on mac, with Elm installed via installer), but my Travis tests have started failing today.

[repo1](https://travis-ci.org/Gizra/elm-hedley/builds/92021462#L145), [repo2](https://travis-ci.org/Gizra/elm-timewatch/builds/92010407)

cc @evancz

**Comment by evancz** [comment]
Generally it is best to use exact versions for a "product" so I'd recommend making [these](https://github.com/Gizra/elm-hedley/blob/master/elm-package.json#L14-L24) precise. Like `2.0.0 <= v <= 2.0.0`

**Comment by evancz** [comment]
This is what @rtfeldman does with NoRedInk code. I'm not sure the exact thing that's causing issues for you though.

**Comment by evancz** [comment]
It's possible that someone updated their package to 0.16 in a weird way. I am really not sure.

**Comment by evancz** [comment]
Ohhh, or maybe because @rtfeldman switched npm to 0.16 already!?

If you are just grabbing it willy nilly, you may be getting a version you did not expect!

**Comment by amitaibu** [comment]
@evancz sounds like a good guess. I'll try it out.

**Comment by amitaibu** [comment]
Indeed. `npm install elm@0.15.1` did the trick. Thanks!

**Comment by evancz** [comment]
Cool, glad we got it sorted out!
