### ISSUE TITLE
"That library and version is not registered" error upon install

### ISSUE THREAD

**Issue by amitaibu** [elm-lang/elm-package#173]
This issue has started yesterday.

My Travis tests are running with npm's `elm@0.15.1` and `elm-package install -y` results with the above error

For example, this test passed yesterday:
<img width="793" alt="set_package_json_to_use_exact-semver_by_amitaibu_ _pull_request__78_ _gizra_elm-hedley" src="https://cloud.githubusercontent.com/assets/125707/11308686/529f57cc-8fc8-11e5-9f69-a0deaf51b72d.png">

But re-running it, now fails

<img width="786" alt="set_package_json_to_use_exact-semver_by_amitaibu_ _pull_request__78_ _gizra_elm-hedley" src="https://cloud.githubusercontent.com/assets/125707/11309020/11763cf0-8fca-11e5-8cf3-951571c48d92.png">

**Comment by amitaibu** [comment]
The offending lib is `truqu/elm-base64`, and the fix is here - https://github.com/truqu/elm-base64/pull/3

Could elm-package provide a more detailed info, for a quicker identification of the problem?

**Comment by jvoigtlaender** [comment]
Maybe your case would have been solved by https://github.com/elm-lang/elm-package/pull/177, just like that pull request would have helped with https://github.com/elm-lang/elm-package/issues/176?

**Comment by amitaibu** [comment]
Indeed. Closing this one. Thanks :)
