### ISSUE TITLE
Newline at EOF on generated elm-package.json

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-package#174]
It's best practice to include a newline at the end of each file, but when you do `elm package install`, the elm-package.json it generates doesn't have one. :crying_cat_face: 

This gets annoying because if you're on a team that follows a newline-at-eof policy via save hooks, every time you do something like `elm package install evancz/elm-http` you get newline-at-eof thrashing on your git diffs.

**Comment by evancz** [comment]
Is this fixed in 0.17.1? I think it is, but check and let me know!

**Comment by rtfeldman** [comment]
Yep! 🎉
