### ISSUE TITLE
Slightly messed up elm-package usage message

### ISSUE THREAD

**Issue by seethemhigh** [elm-lang/elm-package#175]
When I run `elm-package install html` it gives me:
![image](https://cloud.githubusercontent.com/assets/10567153/11336670/4c727690-91f8-11e5-9ae7-a1d39b9218cc.png)

Notice the line that starts with "Examples: ... elm". There's "elm" at the end. I think it should go to the next line to read like "elm package install...". Same thing with the specific version example.

Thanks.

**Comment by jvoigtlaender** [comment]
I guess this is mangled by your terminal. The "Examples ..." text is created by [these lines](https://github.com/elm-lang/elm-package/blob/4a33044cdcb8300c03e1f7aae4a04974acaf88be/src/CommandLine/Arguments.hs#L116-L122). The `unlines` call there is to a Haskell function whose specification is that it "joins lines, after appending a terminating newline to each".

So the question probably is why those terminating newlines don't have the expected effect in your particular terminal.

**Comment by Apanatshka** [comment]
I can reproduce this problem. unlines might not be working properly…
I took a look but can’t find out why it doesn’t work. When I look up
Opt.footer it seems to take a Doc rather than a String… So I don't
understand what's even going on there.

On 23 November 2015 at 13:57, Janis Voigtländer <notifications@github.com>
wrote:

I guess this is mangled by your terminal. The "Examples ..." text is
> created by these lines
> <https://github.com/elm-lang/elm-package/blob/4a33044cdcb8300c03e1f7aae4a04974acaf88be/src/CommandLine/Arguments.hs#L116-L122>.
> The unlines call there is to a Haskell function whose specification is
> that it "joins lines, after appending a terminating newline to each".
>
> So the question probably is why those terminating newlines don't have the
> expected effect in your particular terminal.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elm-lang/elm-package/issues/175#issuecomment-158926674>
> .
>
​

**Comment by jvoigtlaender** [comment]
Ah, in that case maybe instead of turning a string with newlines into a `Doc`, each line should be turned into a `Doc` separately, and then those `Doc`s vertically composed into a new one on the `Doc` level.
