### ISSUE TITLE
Problem with "elm-package diff X.Y.Z" invocation

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-package#179]
The usage instructions for `elm-package diff` are:

```
Usage: elm-package.exe diff ([PACKAGE] [VERSION] [VERSION] | [VERSION])
```

The README of this repository also says that `elm-package diff 1.0.0` is a legal command.

And yet, I get:

```
> elm-package diff 1.0.0
Uh oh, argument "1.0.0" is not a valid PACKAGE

There should be a slash separating the user and project name (user/project)

Usage: elm-package.exe diff ([PACKAGE] [VERSION] [VERSION] | [VERSION])
  Get differences between two APIs

Available options:
  PACKAGE                  A specific package name (e.g. evancz/elm-html)
  VERSION                  Specific version of a package (e.g. 1.2.0)
  VERSION                  Specific version of a package (e.g. 1.2.0)
  VERSION                  Specific version of a package (e.g. 1.2.0)
  -h,--help                Show this help text
```

This is with version 0.16.0 of `elm-package`. A regression, @evancz?

**Comment by dkarter** [comment]
You need to supply the name of the package: 
`elm package evancz/elm-html 1.2.1 2.0.0`

**Comment by evancz** [comment]
@jvoigtlaender, are you running this in a project, or just anywhere?

If you are in a project, that'll be the project name and current version.

**Comment by jvoigtlaender** [comment]
@dkarter, look at the tool's usage instruction I posted. It very clearly indicates that I *don't need* to do what you claim. I know that I *can*, but the tool advertises that I don't *have* to. This is the point of this issue.

@evancz, I was doing that in a project, and I know that the tool should then take the project name and current version as default for the missing data. Just, it wasn't doing that, as you can see in the tool output I posted.

**Comment by evancz** [comment]
I fixed this by creating a custom command line parsing library. This was much easier to resolve when I could stop trying to make everything be an `Applicative` or `Alternative` for no clear reason.

Anyway, here is what I am seeing when I run in `core`:

```
$ elm diff 5.0.0
This is a MAJOR change.

...
```

With all the changes you'd expect to see.

Thanks for the report!
