### ISSUE TITLE
Missing git not detected message in certain scenarios on Windows

### ISSUE THREAD

**Issue by polle-vanhoof** [elm-lang/elm-package#181]
Setup:

* Had git installed (ticking the option in the git installer to not add git to the default windows command prompt)
* Installed elm 0.16 using windows installer
* Made hello.elm file containing:
```
    import Html exposing (span, text)
    import Html.Attributes exposing (class)
    
    main =
        span [class "welcome-message"] [text "Hello, World!"]
```
* Opened default windows command prompt at file location
* executed 'elm-make hello.elm'
* accepted the core language install prompt
* executed 'elm-package install evancz/elm-html'
* Nothing happens, no messages, no regaining control over prompt, it's just stuck
* **executing 'elm-package --version' DOES show there is no installation of git detected and requests me to download it**

How I fixed it:

* Downloaded git again
* Ticked the options to use the default windows shell for git
* Retried 'elm-package install evancz/elm-html'
* Problem was gone

**Comment by evancz** [comment]
Git is no longer required in 0.17.1, so this should be resolved. Thanks for the report!
