### ISSUE TITLE
Document fields in elm-package.json

### ISSUE THREAD

**Issue by Gozala** [elm-lang/elm-package#182]

**Comment by evancz** [comment]
What does this mean?

**Comment by Gozala** [comment]
> What does this mean?

Yeah sorry I should have definitely provided more info, it took me a while myself to recall what the hell did I mean & missing `s` in **field~~s~~** made it even worse.

What I meant is that there are bunch of fields in the `elm-package.json` like `version`, `summary` & more interesting / less obvious ones like `native-modules`. I was unable to find any documentation on what fields does `elm package` recognize and what are constraints on the values for those fields. It would be great if those fields that `elm package` supports where documented somewhere.

**Comment by evancz** [comment]
In the upcoming version of things, if there are problems in your `elm.json` you will get pointed to a link that explains how it works https://github.com/evancz/builder/blob/master/src/Reporting/Error/Assets.hs#L126-L132

So this documentation will get added when that TODO is completed before the release.
