### ISSUE TITLE
Elm-version not verified

### ISSUE THREAD

**Issue by kitofr** [elm-lang/elm-package#183]
Excuse me if this is already adressed, but could not find any issue about it.

I had elm `v 0.15` installed, and tried to run `elm make` on a `v 0.16` project.
That failed. Telling me `dependancy x` was missing (in this case start-app).
I ran `elm-package install` and it reported that everything was A-OK.
Tried `elm make` again and still `dependancy x` missing.

It took me a while, but I then realised that maybe this computer didn't have the lastest version of elm installed. Upgraded and everything went well.

My suggestion however would be to toss a better exception that the dependancy problem if the `elm-package.json` is of a different version.

**Comment by tbrenner** [comment]
I had a similar issue.  With elm v 0.15 installed, I tried to run elm-package install on a v 0.16 project, and saw the following error on Mac OS.

$ elm-package install
elm-package: /usr/bin/git: fileAccess: permission denied (Operation not permitted)

Once I upgraded to 0.16, all went well.

**Comment by evancz** [comment]
Should be fixed by https://github.com/elm-lang/elm-package/commit/39e3fb8b5cadd66998d37ca806a039f583446371#diff-ac236a521931bf4037318327b95f9b00R21

Thanks for the report!
