### ISSUE TITLE
Improve Error "Unable to find a set of packages that will work with your constraints."

### ISSUE THREAD

**Issue by agrafix** [elm-lang/elm-package#184]
SCE: Elm Platform 0.16.0 on Mac 

elm-package.json
```json
{
    "version": "1.0.0",
    "summary": "helpful summary of your project, less than 80 characters",
    "repository": "https://github.com/foo/bar.git",
    "license": "BSD3",
    "source-directories": [
        "./src",
    ],
    "exposed-modules": [],
    "native-modules": true,
    "dependencies": {
        "TheSeamau5/elm-history": "1.0.0 <= v < 2.0.0",
        "agrafix/elm-bootforms": "4.0.0 <= v < 5.0.0",
        "circuithub/elm-list-extra": "3.7.0 <= v < 4.0.0",
        "circuithub/elm-array-extra": "1.1.0 <= v < 2.0.0",
        "elm-lang/core": "3.0.0 <= v < 4.0.0",
        "evancz/elm-effects": "2.0.0 <= v < 3.0.0",
        "evancz/elm-html": "4.0.0 <= v < 5.0.0",
        "evancz/elm-http": "3.0.0 <= v < 4.0.0",
        "evancz/start-app": "2.0.0 <= v < 3.0.0",
        "Bogdanp/elm-combine": "1.1.0 <= v < 2.0.0"
    },
    "elm-version": "0.15.0 <= v < 0.17.0"
}
```

Results in:
```bash
$ elm package install

Error: Unable to find a set of packages that will work with your constraints.
```

It would be very very helpful to provide more information here. What did the resolver try? What was missing? What version could not be used? Why?

**Comment by jvoigtlaender** [comment]
Duplicate. See https://github.com/elm-lang/elm-package/issues/119, and even more importantly, https://github.com/elm-lang/elm-package/pull/177.

Please do check open issues and pull requests before opening an own new issue.

**Comment by bbnnt** [comment]
@jvoigtlaender The answers does not provide a solution... you confirm it does not work, in the process to be solved ?

**Comment by jvoigtlaender** [comment]
I don't have more answers than you can find in #119 and #177. Both of those are still open. Keeping this issue here open as well would serve what purpose?

**Comment by bbnnt** [comment]
Not asking to reopen, felt like asking here instead of adding on those. Thanks for the clarification

**Comment by jvoigtlaender** [comment]
Ah, okay. Sorry I cannot give more positive information about the general issue (about the progress of it being solved).
