### ISSUE TITLE
Accept multiple packages as command line args

### ISSUE THREAD

**Issue by mgold** [elm-lang/elm-package#187]
It would be nice if this command succeeded:

````shell
elm package install jystic/elm-font-awesome evancz/elm-html mgold/elm-animation --yes
````

Instead I get
````
Uh oh, argument "evancz/elm-html" is not a valid VERSION

Must have format MAJOR.MINOR.PATCH (e.g. 1.0.2)
````

It shouldn't be that hard to figure out what's another package and what's another version.

**Comment by jvoigtlaender** [comment]
@mgold, duplicate of https://github.com/elm-lang/elm-package/issues/150?

**Comment by mgold** [comment]
Yup!
