### ISSUE TITLE
Elm-package requires code to have a Github-repo, requires 'repository' key

### ISSUE THREAD

**Issue by arsatiki** [elm-lang/elm-package#188]
I created a project using Elm 0.15.1, which also created my `elm-package.json`. After I upgraded to 0.16, I received the following error:

    Upper case characters are not allowed in package names.

My code does not have a Github repo. It does have a local repo, but it is likely it will never have an existence outside my laptop. Since the repository tag is required, I can't remove it, nor can I leave it empty or even have a `file:` URL pointing at it:

     Missing field "repository", a link to the project's GitHub repo.
    The given URI does not end with .git
    The given domain does not start with <https://github.com/>

## Expected results

- I can develop stuff locally without having to lie about the code having a github repo

## Actual results

- I can't.

**Comment by jvoigtlaender** [comment]
This came up before, and is tracked elsewhere. Closing it as a duplicate here.

See, for example, https://github.com/elm-lang/elm-make/issues/59, https://github.com/elm-lang/elm-package/issues/144#issuecomment-147179541, https://github.com/elm-lang/elm-package/issues/162.

**Comment by arsatiki** [comment]
The bug that tracks this is apparently https://github.com/elm-lang/elm-make/issues/71, which was not listed above. Is that right?

**Comment by jvoigtlaender** [comment]
Well, that or the https://github.com/elm-lang/elm-make/issues/59 I listed above. See also https://github.com/elm-lang/elm-make/issues/71#issuecomment-160901303 and the discussion there.
