### ISSUE TITLE
package download faild when run `elm pakcage install`

### ISSUE THREAD

**Issue by yuffiy** [elm-lang/elm-package#190]
```sh
λ elm package install
Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-lang/core 3.0.0

Do you approve of this plan? (y/n) y
Downloading elm-lang/core

Error: failed with 'InternalIOException Network.Socket.ByteString.recv: failed (No error)' when sending request to
    <http://github.com/elm-lang/core/zipball/3.0.0/>
```
```sh
λ elm package
elm package 0.16.0
#...
```

Anything help.

**Comment by jvoigtlaender** [comment]
What happens if you retry a few times?

**Comment by yuffiy** [comment]
Same result.

Sice I update 0.16 version a few days ago.

**Comment by benjamin-bergia** [comment]
Same issue here.
Just installed elm using npm and I get exactly the same error.

**Comment by yuffiy** [comment]
@benjamin-bergia 应该是墙的问题，

**Comment by bishophu** [comment]
@yuffiy I opened shadowsocks and turn the proxy mode into global, but I still get this error when trying to install elm package.

**Comment by link89** [comment]
@bishophu @yuffiy : I think it is nothing to with network. You can download packages from browser, but it fails when using elm installer or even curl command.

**Comment by yuffiy** [comment]
@link89 :)

Replace `https` to `http` then rebuild elm-package source could word fine.

plz see #194
