### ISSUE TITLE
Adding/removing/changing infix declarations should be signalled by diff, as MAJOR change

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-package#197]
For example, assume that in the `core` package's `Basics.elm` the line

``` elm
infixr 0 <|
```

were replaced by

``` elm
infixl 0 <|
```

At current, `elm-package diff` would ignore that change. But it should actually be considered a MAJOR change under semantic versioning, because it amounts to changing the type of expressions. For example, a client of `core` may contain an expression like `f <| g <| x`. Whether or not this expression is well-typed (given some specific `f`, `g`, `x`) and which type it has (say, if `f`, `g`, `x` are unconstrained and one simply uses type inference) will change between having `infixr` or `infixl` for `<|`. So ignoring that change when computing the diff for `core` breaks the guarantees expected from semantic versioning in a big way.

**Comment by evancz** [comment]
The new implementation checks for that [here](https://github.com/evancz/builder/blob/master/src/Deps/Diff.hs#L141-L144), so it will count as a major change. The diffs also show the associativity and precedence as well, so you can see the change even though the name and type stays the same.
