### ISSUE TITLE
Infix declarations should be included in docs

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-package#198]
... and shown on http://package.elm-lang.org/.

**Comment by evancz** [comment]
In the latest version, all infix operators have precedence and associativity in `docs.json`.

Previously, you would know it is an infix if the name has operators in it. If it does not have assoc/prec info then it is default assoc/prec. Infix operators with custom assoc/prec already had this info listed.

The other thing is to show it on the package website. That should be tracked over there.
