### ISSUE TITLE
elm-get: docs: getDirectoryContents: does not exist (No such file or directory)

### ISSUE THREAD

**Issue by Apanatshka** [elm-lang/elm-package#2]
I'm messing around to see if I can break `elm-get`. 
Here's a way:

1. write a nice `elm_dependencies.json` file. 
2. Add empty elm files. 
3. Try `elm-get publish`

The result is: `elm-get: docs: getDirectoryContents: does not exist (No such file or directory)`. I would prefer a more graceful error message, but it's not a big deal.

**Comment by evancz** [comment]
Is this still an issue with elm-package? If so, lets open an issue that has a complete and minimal example that reproduces the behavior, ideally as a gist that anyone can download as a .zip and dig into.
