### ISSUE TITLE
New Feature: elm-get docs

### ISSUE THREAD

**Issue by maxsnew** [elm-lang/elm-package#20]
I'm not sure if this is a new feature or not. Is there a way to build all of the docs to see what the site will look like when it gets published to library.elm-lang.org? I've messed up docs a few times but I didn't know how to see what they would look like until I publish, at which point I can fix and repush.

I'm imagining a feature where I could run `elm-get docs` in my project and get a directory called `docs` or something that has the pages generated for the website.

**Comment by wetmore** [comment]
Any news on this?

**Comment by evancz** [comment]
Finally this exists http://package.elm-lang.org/help/docs-preview thanks to @burabure!

**Comment by amcsi** [comment]
I would still like to have something like this. Basically a way to view the Elm docs offline

**Comment by Deimos28** [comment]
I would also like to have this. Especially as elm-make --docs=documentation.json seems to return a file containing just the two characters []...

**Comment by vilterp** [comment]
I think it only generates docs for modules in the exposed-modules list in
elm-package.json. Try adding them there

**Comment by Deimos28** [comment]
Thanks! I'll try that.
