### ISSUE TITLE
elm writes to HOME

### ISSUE THREAD

**Issue by sjmackenzie** [elm-lang/elm-package#202]
So when using `elm-make` on nixos I get an error: `elm-make: /homeless-shelter: createDirectory: permission denied (Permission denied)`

This means `elm-make` is writing to `$HOME` and `nix` specifically doesn't allow this so it makes the problem obvious by throwing a `homeless-shelter` error.

Ideally one could pass a `--home` arg to `elm-make` which allows one to override the `$HOME`.

For more info see this issue: https://github.com/elm-lang/elm-make/issues/93
See the corresponding issue for `elm-repl`: https://github.com/elm-lang/elm-repl/issues/109

**Comment by evancz** [comment]
In the upcoming version of things, we will use [the code here](https://github.com/evancz/builder/blob/master/src/Elm/PerUserCache.hs#L32) to manage any cached files. So if you set ELM_HOME to something, you can put the information wherever you want.

**Comment by dunnl** [comment]
What is the current status of this? The link above is broken and I can't find what it was referring to. Also note this issue #280 about `elm-stuff`.

It seems like the `elm` commands should accept command-line overrides or even a configuration file to set these values. That would help it play nicely with systems like Nix. There are already dependencies on `optparse-applicative` and `aeson` so this wouldn't be a major change.

If a consensus forms I'd be glad to contribute.
