### ISSUE TITLE
When requiring a version that doesn't exist, error message is opaque and unhelpful.

### ISSUE THREAD

**Issue by isaacsanders** [elm-lang/elm-package#203]
I was starting a new elm-project, and mistakenly tried to require a version of elm-lang/core that didn't exist. Instead of informing me that this package version does not exist, elm-package informed me that my next dependency in my list, evancz/start-app didn't exist, which I can confirm I am using a version that exists for that package.

After figuring out the issue had to do with a mistake in the acceptable versions range, I fixed it, and the packages installed.

My request: please work on these error messages.

**Comment by jvoigtlaender** [comment]
I think it would be helpful if you showed the exact situation you had (versions you required) and what error message you got.

Also, maybe this pull request has all you need/want: https://github.com/elm-lang/elm-package/pull/177

**Comment by evancz** [comment]
Progress on the error message quality is happening. See https://github.com/elm-lang/elm-package/pull/177#issuecomment-222916014 for details.
