### ISSUE TITLE
Cannot get any package.

### ISSUE THREAD

**Issue by Custodia** [elm-lang/elm-package#207]
All attempts at getting any packages fail with `Error: Unable to find a set of packages that will work with your constraints.`, even attempts to get only the core with `elm package install` fail.

The same behaviour happens on windows and arch linux tested with versions 0.17.0 and 0.16.0 of elm (gotten from npm)

**Comment by JoeyEremondi** [comment]
Can you post your elm-package.json file?

**Comment by Custodia** [comment]
I tried several. Even this auto generated (elm package install)  file doesn't work:

    {
        "version": "1.0.0",
        "summary": "helpful summary of your project, less than 80 characters",
        "repository": "https://github.com/user/project.git",
        "license": "BSD3",
        "source-directories": [
            "."
        ],
        "exposed-modules": [],
        "dependencies": {
            "elm-lang/core": "4.0.0 <= v < 5.0.0"
        },
        "elm-version": "0.16.0 <= v < 0.17.0"
    }

**Comment by JoeyEremondi** [comment]
Looks like there's a bug in the auto-generated packages: it's looking for
the version of Core for 0.17, but it's looking for the 0.16 compiler.

Try:

{
    "version": "1.0.0",
    "summary": "helpful summary of your project, less than 80 characters",
    "repository": "https://github.com/user/project.git",
    "license": "BSD3",
    "source-directories": [
        "."
    ],
    "exposed-modules": [],
    "dependencies": {
        "elm-lang/core": "4.0.0 <= v < 5.0.0"
    },
    "elm-version": "0.17.0 <= v < 0.18.0"
}

**Comment by Custodia** [comment]
That still returns the same error. Does elm package log it's failures somewhere?

**Comment by jvoigtlaender** [comment]
Are you actually sure you are running the 0.17 version of `elm-package`?

Could you please post the shell output of just calling `elm-package` without any parameters?

**Comment by Custodia** [comment]
It was not, that file generated with 0.16.0.

It works now with 0.17.0. Could have sworn that I tried elm package install on an empty directory on 0.17.0 but if that was the case can't think of any reason why it didn't work earlier so it's probably my fault.

Gonna join in on others that the error message should be more descriptive and that it shouldn't add dependencies that are incompatible.
