### ISSUE TITLE
make-info from elm-package.json overwritten on install

### ISSUE THREAD

**Issue by mordrax** [elm-lang/elm-package#212]
After installing a package (`elm-lang/keyboard`) LightTable told me it couldn't find `make-info` and sure enough, it was gone.
It looks like the install script overwrites the `elm-package.json` with what it thinks is required but doesn't take into account other packages piggybacking off the json file.

`make-info` is a key that LightTable uses to find out what to build. e.g
```
    "license": "BSD3",
    "make-info": {"main": "src/main.elm", "out": "dist/js/cotw.js"},
    "source-directories": [
        ".",
        "src"
    ],
```

**Comment by rundis** [comment]
@mordrax That's really a Light Table problem. Not a good idea from my side to mess with the format/keys in elm-package.json.  Close this issue, and open a separate one in https://github.com/rundis/elm-light

**Comment by mordrax** [comment]
Done (https://github.com/rundis/elm-light/issues/18)
