### ISSUE TITLE
Make search for dirname prefix case insensitive

### ISSUE THREAD

**Issue by Janiczek** [elm-lang/elm-package#214]
(Is being addressed in #211.)

```
$ mkdir test-project
$ cd test-project
$ elm-package install janiczek/elm-markov --yes
Downloading elm-community/elm-list-extra
Downloading elm-lang/core
Downloading janiczek/elm-markov

Error: Could not download source code successfully.
```

Cause:
Github username: `Janiczek` (even though you can access a repo with lowercase, the directory inside the zipball is with uppercase)
`elm-package.json` URL: https://github.com/janiczek/elm-markov (which is valid!)

This check in `elm-package` fails, even though it doesn't have to. The package can't be downloaded as a result.

**Comment by bendiksolheim** [comment]
I just struggled quite a bit with this issue myself, with the exact same library that is mentioned in #241 . The error message is a bit misleading – there were no problems downloading the file, but there were problems locating the downloaded files afterwards. Although they may sound the same, there is a subtle difference between the two. In my opinion it would be better if the error message actually said something along the lines of "Could not locate the file user-project.zip in elm-stuff/packages after download" or something. To actually understand what was happening, I ended up reading the Haskell code.

As a workaround if anyone else is struggling with this error: you can rename the downloaded package to what `elm-package` expects after the command fails the first time, and run the install command again. Locate the failed package in `elm-stuff/packages`, convert the folder name to lowercase letters (I think this should fix it in all cases), and run the install command again.

**Comment by karls** [comment]
@bendiksolheim That's exactly what I did as well -- should've pointed this out in my comment/PR.

+1 from me regarding the error message.

**Comment by evancz** [comment]
Fixed in a different way, described in https://github.com/elm-lang/elm-package/pull/211#issuecomment-314271092
