### ISSUE TITLE
the very first hello word did not work

### ISSUE THREAD

**Issue by LuisBL** [elm-lang/elm-package#215]
Hello,

The more simple hello world did not work:

    $ more hello.elm
    import Html exposing (text)

    main =
      text "Hello, World!"

I try to compile it::

    $ elm-make hello.elm
    Could not find package elm-lang/html.

    Maybe your elm-stuff/ directory has been corrupted? You can usually fix stuff
    like this by deleting elm-stuff/ and rebuilding your project.
    $

So try to elm-package it::

    $
    $ elm-package install elm-lang/html

    Error: Unable to find a set of packages that will work with your constraints.

    $

I've read a lot of documentation can't found a starting point.

elm-package version::

    $ elm-package
    elm package 0.17.0

    Usage: elm-package COMMAND
      install and publish elm packages
    ...

and elm-make::

    $ elm-make --version
    elm-make 0.17 (Elm Platform 0.17.0)

    Usage: elm-make [FILES...] [--output FILE] [--yes] [--report FORMAT] [--warn]
                    [--docs FILE] [--prepublish] [--prepublish-core]
      build Elm projects
   ...

**Comment by JoeyEremondi** [comment]
Can we see your elm-package.json file?

**Comment by LuisBL** [comment]
sur, here it is:
```
{
    "version": "1.0.0",
    "summary": "helpful summary of your project, less than 80 characters",
    "repository": "https://github.com/user/project.git",
    "license": "BSD3",
    "source-directories": [
        "."
    ],
    "exposed-modules": [],
    "dependencies": {
        "elm-lang/core": "4.0.1 <= v < 5.0.0",
        "elm-lang/html": "1.0.0 <= v < 2.0.0",
        "evancz/elm-html": "4.0.2 <= v < 5.0.0"
    },
    "elm-version": "0.17.0 <= v < 0.18.0"
}
```

**Comment by JoeyEremondi** [comment]
Remove the evancz html dependency, should fix it.

**Comment by jvoigtlaender** [comment]
What Joey said.
