### ISSUE TITLE
Allow projects to be marked private

### ISSUE THREAD

**Issue by pcstl** [elm-lang/elm-package#219]
Currently, `elm-package` and `elm-make` require every Elm project to have a github repository defined in its `elm-package.json` file. Not having a repository defined will cause a build or install to fail with the following error:

```
Error reading file elm-package.json:
    Missing field "repository", a link to the project's GitHub repo.
    Check out an example elm-package.json file here:
    <https://raw.githubusercontent.com/evancz/elm-html/master/elm-package.json>
```

This is fine when the developer wishes to publish their package to `package.elm-lang.org` or make an open-source applcation, but if the developer does not intend to publish their package, having to supply a repo is a minor annoyance. There is always the option of supplying an invalid repo, but it would be better if there were an option in `elm-package.json` marking the project as private, such that if the project were marked as private, a github repo would not be required.

**Comment by safareli** [comment]
Also someone myght want to use bitbucket or gitlab

**Comment by evancz** [comment]
This will be handled by more comprehensive proposals like https://github.com/elm-lang/elm-make/issues/59
