### ISSUE TITLE
elm-package.json is .gitignored when initializing project on GitHub

### ISSUE THREAD

**Issue by jinjor** [elm-lang/elm-package#221]
I just created a GitHub repository and found that the default `.gitignore` file is like this.

```
# elm-package generated files
elm-package.json
elm-stuff/
# elm-repl generated files
repl-temp-*
```

Should `elm-package.json` be included in this list? I don't understand why it should not be shared. I think this will cause a trouble when publishing it (See #166 ).

I'm not sure where this issue should be reported. Maybe here?

**Comment by evancz** [comment]
It should not be in there. I wasn't involved in making this default setup, but probably someone on elm-discuss or elm-dev or the slack was. I think it's some repo owned by github with a long release cycle.

Hopefully that's enough info to take the next steps because it's everything I know! :)
