### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by Zimmi48** [elm-lang/elm-package#222]
Hello,

I realize this may not get on top of the priority list but I think the following issues should be considered:
## License choice should not be forced onto developers

When creating a new project, `elm make` will automatically generate a `elm-package.json` file. This file contains `"license": "BSD3"`. While such a declaration not being enough for the package to be legally distributed under license BSD3, it can create confusion when people forget to update this (and want to distribute their package under other terms, such as the MIT license say).

An approach a la Cabal could be used instead: it asks you what the license will be, with a default set to `BSD3` (or, more respectfully to `AllRightsReserved`).
## What is the license format to use?

I suppose, from the `BSD3` hint, that you are using the same format as Cabal. I'm not sure what this format exactly is, although there is a description of the underlying type here:
https://www.haskell.org/cabal/release/cabal-latest/doc/API/Cabal/Distribution-License.html

A more "standard" way of encoding the license would be to use SPDX identifiers instead http://spdx.org/licenses/.

But whatever the choice, it needs to be documented.
For instance I'm not sure if I should write `"license": "MPL 2.0"` or `"license": "MPL-2.0"`.
## License should be displayed on package.elm-lang.org

Suppose I am developing a proprietary application in Elm. Then, I'm not allowed to use any GPL library. I don't know if there are any GPL libraries on package.elm-lang.org but so far the various licenses are not well advertised. That's very unfortunate as it would only take one line on the main page of each package to give this information.

Even if developing an open source application, some licenses have some requirements to be met so that the library can be used, so developers should be informed of the license at some point.
## Only free (for the FSF) or open source (for the OSI) license should make it to package.elm-lang.org

I guess this has been the case so far but I don't think it is enforced in any way.

**Comment by Zimmi48** [comment]
When these issues are solved, a nice additional feature would be automatic license compatibility enforcement. It would be in the same spirit as semver enforcement. What it would mean basically is: as soon as one installs a GPL or AGPL package, elm-package announces that this require changing the license of the package being developed and proposes to do it automatically (most other popular licenses including BSD, MIT, Apache 2.0, MPL 2.0 and LGPL do not force any such requirements).

**Comment by Zimmi48** [comment]
To further emphasize that an approach _à la_ cabal is probably the right one, [Libraries.io](https://libraries.io/) shows that on the 8890 projects on Hackage, only 8 are without a license (a mere 0.1%), while on 449 projects on package.elm-lang.org, 122 are without a license (a stunning 27%).

**Comment by evancz** [comment]
This is a lot of stuff all in one issue.

With 0.19 parts of this will be enforced. All licenses must be in the SPDX format, and we will only accept licenses they list as OSI approved.

About displaying it on the package website, that make sense. About having licenses transitively enforced, that also makes sense. About helping people pick licenses and creating license files, that makes sense. The code for managing packages will be moving to a new repo, so I can make an issue outlining these cases there.

Thanks for the report!

**Comment by Zimmi48** [comment]
Thanks! Looking forward to testing 0.19 and future updates.
