### ISSUE TITLE
Race condition in console printing during package download/install?

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-package#226]
Look at the last few lines in this screenshot:
![unbenannt](https://cloud.githubusercontent.com/assets/5853832/16574532/3403898a-4280-11e6-8660-e2e1478dea67.png)

This is with Elm 0.17.1, installed via installer, on Windows 7.

**Comment by evancz** [comment]
Yeah, I actually noticed this before the release, but could not rebuild the windows binaries again. Longer term, I will make it so you can configure how many downloads are happening concurrently. I suspect most users will want infinity as the cap, but in resource constrained environments it make be necessary to cap things. When I make those changes, I will fix this.

**Comment by evancz** [comment]
This is resolved in the new binaries. All terminal output is managed by a single thread so messages are sure to be printed one-at-a-time, even if the work itself is interleaved.
