### ISSUE TITLE
Can't install successfully published package

### ISSUE THREAD

**Issue by turboMaCk** [elm-lang/elm-package#242]
Hello.

I've ran into issue while trying to install my successfully published package using `elm package install`

### Error
actual error log is following:

```
Some new packages are needed. Here is the upgrade plan.

  Install:
    turbomack/chaetree 1.0.1

Do you approve of this plan? [Y/n] y
Starting downloads...

  ✗ turbomack/chaetree 1.0.1
Error: Problem when downloading the turbomack/chaetree 1.0.1 code.
```

### Package
This happens for both https://github.com/turboMaCk/chae-tree/tree/1.0.1 and 
https://github.com/turboMaCk/chae-tree/tree/2.0.0

### More debugging info

When I look to `~/.elm/0.17.1/package/turbomack/chaetree/[version]` I see only `elm-package.json`. File is identical to one from github under specific version.

```
cat ~/.elm/0.17.1/package/turbomack/chaetree/2.0.0/elm-package.json
{
    "version": "2.0.0",
    "summary": "Create multi-level navigation in elm easily.",
    "repository": "https://github.com/turbomack/chaetree.git",
    "license": "BSD-3-Clause",
    "source-directories": [
        "src"
    ],
    "exposed-modules": [
        "Chae.Id",
        "Chae.Node",
        "Chae.Tree"
    ],
    "dependencies": {
        "elm-lang/core": "4.0.5 <= v < 5.0.0"
    },
    "elm-version": "0.17.1 <= v < 0.18.0"
}
```

### Additional info

At first I thought that it might be same issue as described here: https://github.com/elm-lang/elm-package/pull/211 (there is also opened PR https://github.com/elm-lang/elm-package/pull/241) because:

- My github user name is `turboMaCk` but lowercase version is used in repository (`turbomack`)
    - Upper case letters are not allowed in repository name so I make whole repository field lowercase
- Original name of github repository was `ChaeTree`.

So I tried to:

- Rename repository to lower case version `chaetree`
- Change my user name to lowercase `turbomack`

This **did not** help.

### Question

I guess I made some mistake in settings but I'm still not sure if cases are the only problem. I'm also thinking about renaming package and republishing it with fixed user name (`turboMaCk`) and new name `chae-tree`. Anyway I'm not sure if this solves the issue and I don't want to spam http://package.elm-lang.org with more invalid packages.

I've raised the question about this on elmlang.slack.com but none seems to be familiar with this.

Feel free to remove invalid package from repository if you want to.

**Comment by evancz** [comment]
Okay, I took it down for you. Republish it as `turboMaCk/chae-tree` and make sure that matches the name on github including capitalization.

The lower case restriction is on the package names. We can't control people's user names, and I don't think that'd make any sense to try to do.

**Comment by turboMaCk** [comment]
Thank you @evancz!

This policy seems reasonable to me.

Have a great day and thanks for fast feedback.

**Comment by evancz** [comment]
No problem, thanks for bringing this up. Maybe it'll be possible to have additional checks some point later so this kind of thing cannot happen. Working on package stuff like this is high on the todo list.
