### ISSUE TITLE
Using exact deps makes elm-package not resolve dependencies correctly

### ISSUE THREAD

**Issue by eeue56** [elm-lang/elm-package#243]
#  Problem

Elm-package with exact versions will not warn when it fails to satisfy a dep correctly.

elm-package:
```
 "dependencies": {
        "NoRedInk/nri-elm-css": "1.4.0 <= v <= 1.4.0",
        "elm-lang/core": "4.0.5 <= v < 5.0.0",
        "elm-lang/html": "1.1.0 <= v < 2.0.0",
        "rtfeldman/elm-css": "6.0.0 <= v <= 6.0.0"
    },
```

- run `elm-package install` (elm-css will be version 3.1.2, not 6.0.0 as expected)

![screen shot 2016-10-06 at 02 25 33](https://cloud.githubusercontent.com/assets/1139198/19136344/2fc3ae56-8b6c-11e6-8902-d1f85079ed1d.png)

We discovered this in production, when suddenly our code was expecting elm-css 6.0.0 but 3.1.2 was getting installed. I checked everything else - it seems like loose calculations will get an error message, exact deps won't.

**Comment by rtfeldman** [comment]
Full SSCCE to reproduce:

1. Put this exact `elm-package.json` in an empty directory

```
{
    "version": "1.0.0",
    "summary": "helpful summary of your project, less than 80 characters",
    "repository": "https://github.com/user/project.git",
    "license": "BSD3",
    "source-directories": [
        "."
    ],
    "exposed-modules": [],
    "dependencies": {
        "NoRedInk/nri-elm-css": "1.4.0 <= v <= 1.4.0",
        "elm-lang/core": "4.0.5 <= v <= 4.0.5",
        "elm-lang/html": "1.1.0 <= v <= 1.1.0",
        "rtfeldman/elm-css": "6.0.0 <= v <= 6.0.0"
    },
    "elm-version": "0.17.1 <= v <= 0.17.1"
}
```

2. Run `elm-package install --yes`

**Expected:**

Error - unsatisfiable constraints because `nri-elm-css 1.4.0` [requires `"elm-css": "3.0.0 <= v < 4.0.0"`](https://github.com/NoRedInk/nri-elm-css/blob/1.4.0/elm-package.json) whereas this elm-package.json requires `"elm-css": "6.0.0 <= v <= 6.0.0"`

**Actual:**

Succeeds, and `elm-stuff/exact.dependencies.json` shows that `elm-css` 3.1.2 was installed instead of 6.0.0, even though our application code depended on 6.0.0.

Full `exact-dependencies.json`:
```js
{
    "elm-lang/virtual-dom": "1.1.1",
    "rtfeldman/elm-css-util": "1.0.1",
    "elm-lang/html": "1.1.0",
    "rtfeldman/elm-css": "3.1.2",
    "NoRedInk/nri-elm-css": "1.4.0",
    "elm-lang/core": "4.0.5"
}
```

**Comment by evancz** [comment]
@rtfeldman privately said to me that he thinks this *started* with 0.17 and did not exist before that. Can someone confirm this? If we know it happens in 0.17 but not with 0.16 it should be easier to track down the problem.

**Comment by eeue56** [comment]
Also broken in 0.16:

elm-package.json
```
{
    "version": "1.0.0",
    "summary": "helpful summary of your project, less than 80 characters",
    "repository": "https://github.com/user/project.git",
    "license": "BSD3",
    "source-directories": [
        "."
    ],
    "exposed-modules": [],
    "dependencies": {
        "NoRedInk/nri-elm-css": "1.1.0 <= v < 2.0.0",
        "elm-lang/core": "3.0.0 <= v < 4.0.0",
        "rtfeldman/elm-css": "2.1.0 <= v <= 2.1.0"
    },
    "elm-version": "0.16.0 <= v < 0.17.0"
}

```

gives 

exact-dependencies.json

```
{
    "rtfeldman/elm-css-util": "1.0.0",
    "rtfeldman/elm-css": "2.2.0",
    "NoRedInk/nri-elm-css": "1.1.0",
    "elm-lang/core": "3.0.0"
}
```

**Comment by eeue56** [comment]
I tried this out on 0.18, and this seems fixed:
```
noah@Noahs-MacBook-Pro ~/d/n/dip> ../Elm-Platform/master/.cabal-sandbox/bin/elm-package install
Error: I cannot find a set of packages that works with your constraints.

One way to rebuild your constraints is to clear everything out of the
"dependencies" field of elm-package.json and add them back one at a time with
`elm-package install`.

I hope to automate this in the future, but at least there is a way to make
progress for now!

```
