### ISSUE TITLE
download bullets look weird on Japanese Windows 10

### ISSUE THREAD

**Issue by giisyu** [elm-lang/elm-package#251]
environment : 
windows 10
elm-make 0.18 (Elm Platform 0.18.0)
elm-package 0.18.0
Command Prompt

```
>elm package install elm-lang/navigation -y
Starting downloads...

  笳・elm-lang/navigation 2.0.0

笳・elm-lang/dom 1.1.1
Packages configured successfully!
```

**Comment by stkb** [comment]
Wasn't sure whether to open a separate issue for this but the bullets don't show properly either in English code pages, eg OEM United States (437) or ANSI Latin 1 Western European (1252).

<img width="360" alt="437" src="https://cloud.githubusercontent.com/assets/6125444/22404832/4d8d3c4a-e639-11e6-8550-34e075c52edf.png">

Even after switching to code page 65001 (UTF-8), the bullets show, but have some extra characters after them.

<img width="357" alt="65001" src="https://cloud.githubusercontent.com/assets/6125444/22404841/80075ab6-e639-11e6-9c1b-4c5c210b8af3.png">

I noticed there was a commit back in June 2016 to fix this, but it was later reverted.

**Comment by evancz** [comment]
The next release will check if it is windows and do an uglier character https://github.com/evancz/builder/blob/master/src/Reporting/Progress/Terminal.hs#L214-L229

Thanks for the report!
