### ISSUE TITLE
When two packages use the same Module.Name, neither can be used.

### ISSUE THREAD

**Issue by sgillis** [elm-lang/elm-package#257]
Installing libraries that expose modules with the same name results in problems. For example, `mdgriffith/elm-style-animation` and `mgold/elm-animation` both expose `Animation`. When trying to compile, I get this error:

```
I found multiple modules named 'Animation'.

Module '<mymodule>' is trying to import it.

Modules with that name were found in the following locations:

    package mdgriffith/elm-style-animation
    package mgold/elm-animation
```

It seems that this could become a bigger problem when the number of packages grows.

I am using Elm 0.18

**Comment by evancz** [comment]
Tracking in https://github.com/elm-lang/elm-compiler/issues/1625 meta issue. Thanks for the report!
