### ISSUE TITLE
Elm package repo downtime?

### ISSUE THREAD

**Issue by stil4m** [elm-lang/elm-package#258]
Today I got this message:

```
Message:
    Error: The following HTTP request failed.
<http://package.elm-lang.org/all-packages?elm-package-version=0.18&since=2017-01-19%2006%3A43%3A07.230381%20UTC>
FailedConnectionException2 "package.elm-lang.org" 80 False getAddrInfo: does not exist (nodename nor servname provided, or not known)
```

This was around 11:30AM Central European time.

I assume that the package repo was down. Was this the problem, and how can we resolve this?

* What is the resiliency on the package manager?
* Can we fallback on local cached resources when the package manager is down?

Are these questions that will be resolved in 0.19 and can users of Elm take counter measures at this time?

**Comment by evancz** [comment]
This is a pretty open ended question that has been discussed quite a bit by core folks.

0.19 will be improving things by creating a per-user cache of all past downloads. That means if you have downloaded something once, you do not need to download it again, thereby reducing the overall load. 0.19 is also setting up a variety of longer term improvements.

In any case, I prefer to use github issues for tracking concrete bugs and work, so this would be a better discussion for slack or one of the mailing lists.
