### ISSUE TITLE
Can't seem to lock down elm-lang/core to 5.0.0

### ISSUE THREAD

**Issue by tracker-common** [elm-lang/elm-package#259]
After a conversation with @eeue56 on slack/elm-dev about the core 5.1.0 issues, I was attempting to lock down core to 5.0.0 with no success.  I tried locking down every package an removing elm-stuff, but `elm package install` always goes for 5.1.0 (or 51.1 when it came out).  I'm not sure what the scope of this bug is, but Noah said I should make an issue here.

For reference, here is the elm-package:

```
{
    "version": "1.0.0",
    "summary": "***elided***",
    "repository": "***elided***",
    "license": "commercial",
    "source-directories": [
        "app/bundles/Dashboard/src",
        "app/bundles/Dashboard/tests"
    ],
    "exposed-modules": [],
    "dependencies": {
        "Fresheyeball/elm-function-extra": "3.0.0 <= v < 3.0.1",
        "Fresheyeball/elm-return": "6.0.3 <= v < 6.0.4",
        "elm-community/elm-test": "3.1.0 <= v < 3.2.0",
        "elm-community/json-extra": "2.0.0 <= v < 2.0.1",
        "elm-community/list-extra": "4.0.0 <= v < 4.0.1",
        "elm-community/maybe-extra": "3.0.0 <= v < 3.0.1",
        "elm-community/shrink": "2.0.0 <= v < 2.0.1",
        "elm-community/string-extra": "1.1.1 <= v < 1.1.2",
        "elm-lang/core": "5.0.0 <= v < 5.0.1",
        "elm-lang/dom": "1.1.1 <= v < 1.1.2",
        "elm-lang/html": "2.0.0 <= v < 2.0.1",
        "elm-lang/http": "1.0.0 <= v < 1.0.1",
        "ggb/numeral-elm": "1.2.3 <= v < 1.2.4",
        "mgold/elm-random-pcg": "4.0.2 <= v < 4.0.3",
        "rtfeldman/elm-validate": "1.1.3 <= v < 1.1.4",
        "rtfeldman/node-test-runner": "3.0.0 <= v < 3.0.1"
    },
    "elm-version": "0.18.0 <= v < 0.18.1"
}
```

If you have questions, please reference @jschomay if possible.
Thanks!

**Comment by evancz** [comment]
In 0.19 this info will live in `elm.json` and for an application, all dependencies must have exact versions. That means all applications will have a lock file by default. That should resolve whatever is going on here.

**Comment by evancz** [comment]
And before people freak out, there are different types of `elm.json` files. One for `application` and one for `package`. In an application, you must have exact dependencies that serve as a lock file. In a package, you must have version ranges.
