### ISSUE TITLE
If README does not exist, elm-package should complain before it tells you to tag the release.

### ISSUE THREAD

**Issue by avh4** [elm-lang/elm-package#261]
For a new package, there may not yet be a README file.  `elm-package publish` will instruct you to publish the 1.0.0 tag before it checks for the existence of the README, so if no README exists at that time, the tag will need to be rewritten.  `elm-package` should instead warn about the missing readme before proceeding with other checks.

**Comment by evancz** [comment]
Good idea, thanks for sharing it here!
