### ISSUE TITLE
Why force GitHub as the place to host code?

### ISSUE THREAD

**Issue by heronblade** [elm-lang/elm-package#267]
In `Description.hs` the following code 
```
dropDomain :: String -> Either String String
dropDomain string =
  let
    http = "http://github.com/"
    https = "https://github.com/"
  in
    if List.isPrefixOf http string then
        Right (drop (length http) string)

    else if List.isPrefixOf https string then
        Right (drop (length https) string)

    else
        Left (repoProblem "The given domain does not start with <https://github.com/>")
```

forces the `repository` field in `elm-package.json` to start with `http://github.com/` or `https://github.com/`.  I wanted to host my code elsewhere, and got an error message, I had to enter just a random `https://github.com/random.git` to get `elm-package install` to run correctly.

Can this requirement be changed?

I am using ELM `0.18.0` on Mac OS 10.12.3.
To reproduce the error, create a `elm-package.json` and change the `repository` field to something that does not start with `http://github.com/` or `https://github.com/`.

**Comment by jvoigtlaender** [comment]
See https://github.com/elm-lang/elm-package/issues/189 and https://github.com/elm-lang/elm-make/issues/59 and various other issues referenced from those.

Your new issue here is redundant.

**Comment by heronblade** [comment]
@jvoigtlaender: thanks for pointing that out I didn't see those issues earlier. closing this
