### ISSUE TITLE
`elm-get install` Unnecessary Questions

### ISSUE THREAD

**Issue by maxsnew** [elm-lang/elm-package#28]
When you `elm-get install` a library, you will always be prompted with a question for whether or not you want to add the file to your `elm_dependencies.json`, even if you already have it there!

An example of the interaction:
```
$ elm-get install automaton
Cloning repo evancz/automaton
Checking out version 0.1.0.1
Should I add this library to your elm_dependencies.json file? (y/n): y
evancz/automaton 0.1.0.1 is already in elm_dependencies.json.
Do you want to replace it with version 0.1.0.1? (y/n): y
Success!
```

Ideally this should not ask to add if you already have it listed with the dependency you've requested, but it should ask to update if you have an earlier version.

**Comment by evancz** [comment]
Should be resolved in `elm-package`. Let's open a new one if not!
