### ISSUE TITLE
Native review for FileReader

### ISSUE THREAD

**Issue by piotrcyr** [elm-lang/elm-package#32]
[`FileReader`](https://github.com/piotrcyr/elm-filereader)  module, in short, makes it possible to read in a file passed by user.
The module introduces:
* abstraction of `File`s and `Blob`s
* html <input type="file"/> input control
* a way to enhance any `Element` with a capability to open file selection dialog on click
* ability to get files from user's drag and drop action
* abstraction of a `FileReader`
* reading (d'uh!) and slicing files

If you have any questions about implementation details [you can ask them here](https://groups.google.com/forum/#!topic/elm-discuss/N8Je65jPrco) or [mail the creator directly](mailto:neocyran@gmail.com)

**Comment by Apanatshka** [comment]
The `elm-package` tool says to open these reviews on the [package.elm-lang.org issues list](https://github.com/elm-lang/package.elm-lang.org/issues). Can you move it there?

**Comment by piotrcyr** [comment]
This issue was moved to elm-lang/package.elm-lang.org#49
