### ISSUE TITLE
elm-get install : no proxy support

### ISSUE THREAD

**Issue by fredericlb** [elm-lang/elm-package#44]
When trying to install a new package from Github, elm-get does not check for HTTP_PROXY and HTTPS_PROXY env vars, meaning that it won't hit the proxy but will try and fail to fetch url directly.

**Comment by evancz** [comment]
Is this still an issue with `elm-package`? @kfish, do you know any more details about how to add a feature something like this?

**Comment by johnpmayer** [comment]
I think this has always worked on unix. I'm looking to do the same on Windows now.

``` shell
$ echo $http_proxy
http://10.0.0.216:3128
$ echo $https_proxy
http://10.0.0.216:3128
$ elm-make
Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-lang/core 1.1.0

Do you approve of this plan? (y/n) y
Downloading elm-lang/core
Packages configured successfully!
Compiled 32 files
```

**Comment by johnpmayer** [comment]
Yeah, does the same on Windows if you set http_proxy. It would be cool to also handle registry (Internet Settings).

http://hackage.haskell.org/package/HTTP-4000.1.1/docs/src/Network-HTTP-Proxy.html#registryProxyString

But I think we can close this now

**Comment by kfish** [comment]
@evancz The specific problem I was having was https://github.com/elm-lang/elm-package/issues/100, which my colleague @jystic has recently tracked down.

**Comment by NigelThorne** [comment]
I still get a crash on windows... 

elm-make --yes node-elm-loader\example\ticking_port.elm --output node-elm-loader\example\ticking_port.js

failed with 'TlsException (HandshakeFailed (Error_Packet_Parsing "Failed reading
: invalid header type: 72\nFrom:\theader\n\n"))' when sending request to
    <http://github.com/elm-lang/core/zipball/2.1.0/>

(I'm trying to get https://github.com/sonnym/node-elm-loader example to run on windows).. behind a proxy server.
