### ISSUE TITLE
Website: Dead/outdated links

### ISSUE THREAD

**Issue by jastice** [elm-lang/elm-package#49]
on the [Documentation](http://library.elm-lang.org/Documentation.html) page, several links point to `/catalog/evancz-Elm/0.10.1/`, which gives a 404. Links to the Maybe and Either library implementations point to `https://github.com/evancz/Elm/blob/master/libraries/` rather than the repo in the elm-lang org.

**Comment by evancz** [comment]
Can you send PRs? It is difficult to hunt this kind of thing down. If not, let's close this one!

**Comment by evancz** [comment]
If not a PR, at least a link to the particular line number that is messed up?

**Comment by jastice** [comment]
The page in question doesn't even exist anymore, so I think this is obsolete :)

**Comment by evancz** [comment]
Another way to fix things :P Thanks for the report!
