### ISSUE TITLE
Native review for elm-midi

### ISSUE THREAD

**Issue by youpy** [elm-lang/elm-package#76]
https://github.com/youpy/elm-midi

This library provides function for working with MIDI using Web MIDI API.
It currently supports receiving MIDI messages from MIDI inputs.

**Comment by Apanatshka** [comment]
The `elm-package` tool says to open these reviews on the [package.elm-lang.org issues list](https://github.com/elm-lang/package.elm-lang.org/issues). Can you move it there?

**Comment by youpy** [comment]
ok.
