### ISSUE TITLE
Using a fork of elm-core

### ISSUE THREAD

**Issue by rehno-lindeque** [elm-lang/elm-package#91]
We're trying to figure out how to use a fork of `elm-core`. One idea I had was to do something like this

```sh
$ mv elm-stuff/packages/elm-lang/core/1.1.0/ elm-stuff/packages/elm-lang/core/1.1.99/

$ subl elm-stuff/exact-dependencies.json # bump core to 1.1.99

$ elm-make ... # works ok
Compiled 83 files                                                   

$ elm-package install # doesn't work ok
Some new packages are needed. Here is the upgrade plan.

  Remove:
    circuithub/elm-function-extra
    circuithub/elm-json-extra
    elm-lang/core
    evancz/elm-html
    evancz/local-channel
    evancz/virtual-dom

Do you approve of this plan? (y/n) 
```

The only problematic thing is having `elm-package install` insist on deleting packages... I wonder if it would be ok to ignore packages with a version number greater than what is published? This seems like the tiniest (perhaps temporary) fix I can think of for doing this.

**Comment by evancz** [comment]
I think @laszlopandy knows about how to do tricks here. We have the same issue for unreleased versions of core + testing.

What kind of changes are you making in core?

**Comment by rehno-lindeque** [comment]
Oh so basically - it is this PR we're after: https://github.com/elm-lang/core/pull/120 - we think this is going to make a huge difference to the board rendering widget @TheunisKotze is building at the moment

**Comment by evancz** [comment]
I believe tricks like this will become possible with more comprehensive changes like https://github.com/elm-lang/elm-make/issues/59 so I'm going to close in favor of that.
