### ISSUE TITLE
Changing Elm Version Doesn't Affect `elm package bump`

### ISSUE THREAD

**Issue by maxsnew** [elm-lang/elm-package#97]
I just changed `IO` from `elm-version` 0.14.0 to 0.15.0, but elm-package won't let me release with a major version bump, only a patch bump.

1. Why can't I tell elm package that I know better and that it should be a major version bump?
2. Why doesn't it take elm-version into account?

**Comment by evancz** [comment]
These are new features that are not covered right now, sorry for the trouble! Point 1 is on the map. I guess the bigger question for 2 is "Is it always a breaking change to change constraints?"

**Comment by evancz** [comment]
Opened #165 to better track this, need to add it!
